name: Bug Report
description: Report a bug in T.A.R.S
title: "[BUG] "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! 🐛
        
  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: What happened?
      placeholder: T.A.R.S did something unexpected...
    validations:
      required: true
      
  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: How can we reproduce this?
      placeholder: |
        1. Run `tars health`
        2. See error...
    validations:
      required: true
      
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What should have happened?
    validations:
      required: true
      
  - type: input
    id: version
    attributes:
      label: T.A.R.S Version
      description: Run `tars version`
      placeholder: v0.1.0
    validations:
      required: true
      
  - type: input
    id: python
    attributes:
      label: Python Version
      description: Run `python --version`
      placeholder: 3.10.0
    validations:
      required: true
      
  - type: input
    id: k8s
    attributes:
      label: Kubernetes Version
      description: Run `kubectl version --short`
      placeholder: v1.28.0
      
  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other information?
