name: Feature Request
description: Suggest a feature for T.A.R.S
title: "[FEATURE] "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! 💡
        
  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this solve?
      placeholder: I'm always frustrated when...
    validations:
      required: true
      
  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How should T.A.R.S solve this?
      placeholder: T.A.R.S could...
    validations:
      required: true
      
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: What other solutions did you think about?
      
  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any mockups, examples, or references?
